[project]
name = "fine-tuning-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch",
    "transformers>=4.44",
    "datasets>=2.20",
    "peft>=0.12",
    "accelerate>=0.34",
    "trl>=0.9.6",
]
